
trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  repositoryName: 'pipelines-javascript-docker'

steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
      repository: $(repositoryName)
      command: build
      Dockerfile: app/Dockerfile